### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by martijndierckx** [louwrentius/showtools#10]
Downloaded the latest version of your scripts. But I'm getting a decoding error.
`show disk -mSs` works but once I start requesting extra things like temp etc, the script returns an error.

Any ideas?

Setup:
- Ubuntu 20.04.1 (clean install)
- Python 3.8.5 (came with ubuntu)
- Smartmontools (installed via apt): smartctl 7.1 2019-12-30 r5022 [x86_64-linux-5.4.0-58-generic] (local build)

```
$ sudo showtools-1.0.1/show disk -mSsftHrRP
Traceback (most recent call last):
  File "showtools-1.0.1/show", line 765, in <module>
    main()
  File "showtools-1.0.1/show", line 165, in main
    devicedata = process_device(device, args)
  File "showtools-1.0.1/show", line 564, in process_device
    disktemp = get_parameter_from_smart(disksmart,
  File "showtools-1.0.1/show", line 367, in get_parameter_from_smart
    data = data.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by louwrentius** [comment]
Thanks for your report. (Dag Martijn)

Would you mind sending me the smart data output of all drives? 

`for x in `ls -1 /dev/sd?`; do echo $x; smartctl -a $x; done > /tmp/smartoutput.txt`

You can drop the smartoutput.txt as a file here.

Maybe my code is chocking on some (lack of) smart output. If no output is generated, you might want to add -d ata to the smartctl parameters. Many thanks in advance.

**Comment by martijndierckx** [comment]
Here you go
[smartoutput.txt](https://github.com/louwrentius/showtools/files/5751075/smartoutput.txt)

**Comment by louwrentius** [comment]
Thanks a lot, I suspect that it doesn't cope well with this section:

> === START OF INFORMATION SECTION ===
> Vendor:               VMware
> Product:              Virtual disk

I'll try and fix the error handling.

**Comment by louwrentius** [comment]
I've created a branch 'development' with the fixed code. I believe I resolved the issue, but you'll be the judge of that.

**Comment by martijndierckx** [comment]
That did it!

Thanks for the swift response!
